# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare node.js orb
  node: circleci/node@4.1.0
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

nightly:
  triggers:
    - schedule:
        cron: "2 0 * * *"
        filters:
          branches:
            only:
              - master
#First - minute
# second - hour
# Day of month
# Month
# day of week
# * 1 * * * => Every one hour
# 10 * * * * => Every 10 mins
# * * * * 1 => Every Monday

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
