version: 2.1
description: |
  Newman is a collection runner for Postman.
  It allows you to effortlessly run and test a Postman collection.
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Org_service_postman_automation/Organization-Dev.postman_collection.json -e ./Org_service_postman_automation/OrgDevTest.postman_environment.json
