# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    # use the official newman docker image via newman/postman-newman-docker executor
    executor: newman/postman-newman-docker
    
    steps:
      # checkout step is optional if you are not referencing any files from the project
      - checkout
      
      # use newman-run command
      - newman/newman-run:
          collection: ./postman_automation/Organization-Dev.postman_collection.json environment: ./postman_automation/OrgDevTest.postman_environment.json
