version: 2.1

orbs:
  newman: postman/newman@0.0.2
  slack: circleci/slack@3.4.2
  
nightly:
  triggers:
    - schedule:
        cron: "10 * * * *"
        filters:
          branches:
            only:
              - master

jobs:
  #newman-collection-run:
  Postman:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          name: Postman Org Collections - Dev
          collection: ./Org_service_postman_automation/Organization-Dev.postman_collection.json -e ./Org_service_postman_automation/OrgDevTest.postman_environment.json
